# Generated by Django 4.1.2 on 2023-06-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=30)),
            ],
        ),
    ]
